targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dartdevc
          environment:
            TYPE: $TYPE
            PROJECT_ID: $PROJECT_ID
            PRIVATE_KEY_ID: $PRIVATE_KEY_ID
            PRIVATE_KEY: $PRIVATE_KEY
            CLIENT_EMAIL: $CLIENT_EMAIL
            CLIENT_ID: $CLIENT_ID
            AUTH_URI: $AUTH_URI
            TOKEN_URI: $TOKEN_URI
            AUTH_PROVIDER_X509_CERT_URL: $AUTH_PROVIDER_X509_CERT_URL
            CLIENT_X509_CERT_URL: $CLIENT_X509_CERT_URL
            UNIVERSE_DOMAIN: $UNIVERSE_DOMAIN
